DROP TABLE giro CASCADE;
DROP TABLE gara CASCADE;
DROP TABLE circuito CASCADE;
DROP TABLE vettura CASCADE;
DROP TABLE motore CASCADE;
DROP TABLE pilota CASCADE;
DROP TABLE contratto CASCADE;
DROP TABLE team_member CASCADE;
DROP TABLE utilizzo CASCADE;
DROP TABLE fornitura CASCADE;
DROP TABLE strumento CASCADE;
DROP TABLE fornitore CASCADE;
DROP TABLE settore CASCADE;
DROP INDEX idx_giro_1
